# -*- coding: utf-8 -*-
"""github assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wpLcHYTsH_BIbJAMqtcMDx4Zn4zShgL-
"""

import pandas as pd
import numpy as np

print("Mark of Animesh") 
marks=[97,95,81,94,93] 
sub_name=['Maths', 'Science', 'Computer', 'Social', 'English'] 
ind=pd.Series (marks,index=sub_name) 
dt=pd.DataFrame(
    {
        "Subjects":pd.Series(sub_name), 
        "Marks": pd. Series (marks), 
        "Grade":pd. Series(['A', 'B','C','A','A']), 
        "Qualification":'Pass', 
        "Rank": np.array([1]*5),
    }
)
dt1=pd.DataFrame(
    {
      "Remarks":pd.Categorical(["Great Job"]),
    }
)
dtfl=pd.concat([dt, dt1]) 
print(dtfl)

marks=[97,94,81,94,91] 
sub_name=['Maths','Science','Computer','Social','English'] 
ind-pd.Series(marks,index=sub_name) 
dt=pd.DataFrame(
    {
        "Subjects":pd.Series (sub_name), 
        "Marks":pd.Series (marks), 
        "Grade" : pd.Series(['A','B','C','A','A']), 
        "Qualification":'Pass', 
        "Rank":np.array([1]*5),
    }
)    
print(marks) 
mrk=np.mean(marks) 
mrk1=np.median (marks)
print("Mean marks is:",mrk) 
print("Median mark is:",mrk1) 
x=np.percentile(marks, 80, axis=None, interpolation='midpoint') 
print("Percentile function:",x) 
y=np.var(marks, axis=None, dtype=None, ddof=0) 
print("Variance function:",y) 
z=np.std(marks, axis=None, dtype=None, ddof=0) 
print("Standard deviation:",z)

print("Mark of Animesh") 
marks=[97,94,81,95,93] 
sub_name=['Maths', 'Science', 'Computer', 'Social', 'English'] 
ind=pd.Series(marks, index=sub_name) 
dt=pd.DataFrame(
    {
        "Subjects":pd.Series(sub_name), 
        "Marks": pd. Series (marks), 
        "Grade":pd. Series(['A', 'B','C','A','A']), 
        "Qualification":'Pass', 
        "Rank": np.array([1]*5),
    }
)    
dt1=pd.DataFrame(
    {
        "Remarks":pd.Categorical(["Great Job"]),
    }
)    
dtfl=pd.concat([dt, dt1]) 
print(dtfl)